[package]
name = "daachorse"
version = "0.2.1"
edition = "2018"
authors = [
    "Koichi Akabe <vbkaisetsu@gmail.com>",
    "Shunsuke Kanda <shnsk.knd@gmail.com>",
]
description = "Daac Horse: Double-Array Aho-Corasick"
license = "MIT OR Apache-2.0"
homepage = "https://github.com/legalforce-research/daachorse"
repository = "https://github.com/legalforce-research/daachorse"
readme = "README.md"
keywords = ["string", "search", "text", "aho", "multi"]
categories = ["text-processing"]
autotests = false
exclude = [".*"]

[dependencies]
byteorder = "1.4.3"  # Unlicense or MIT
serde = "1.0"  # MIT ot Apache-2.0

[dev-dependencies]
bincode = "1.3"  # MIT
rand = "0.8.4"  # MIT or Apache-2.0

[workspace]
members = [
    "bench",
]
