[package]
name = "daacfind"
version = "0.1.0"
edition = "2021"

[dependencies]
daachorse = { path = ".." }  # MIT or Apache-2.0
structopt = "0.3"  # MIT or Apache-2.0
termcolor = "1.1"  # Unlicense or MIT
